apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hetzner-robot-state
  labels:
    app.kubernetes.io/name: hetzner-robot-provisioner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sata
  resources:
    requests:
      storage: 1Gi
